### PR TITLE
Fixed plugin and core class

### PR DESCRIPTION
**Pull request by Aeysol**
Sorry for the trouble, forgot to update the core class with the changed plugin name. Also fixed some strings in the ThermalFoundationPlugin.java file.

Regards.

### CODE REVIEW

**Comment by LordBlackhole** [comment]
I'm done with modding for now. If you want you can take over any and all mods of mine you would like. No problem.

**Comment by Aeysol** [comment]
I am sorry to hear that. I'll try my best to maintain the mods as good as I can.

**Comment by LordBlackhole** [comment]
I gave up largely because I got tired of my code breaking with every single Minecraft update, with no mod API in site, and I just don't have enough time with my job now to maintain it like that. That's why the code is frozen half-way through updates. Good luck with it.

**Comment by Aeysol** [comment]
Godspeed, LordBlackhole. And thanks for a decent code base!

**Pull request merged**
